{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kubenetmon-server.fullname" . }}
  labels:
    {{- include "kubenetmon-server.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      {{- include "kubenetmon-server.selectorLabels" . | nindent 6 }}
{{- end }}
