{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) .Values.metrics.enabled }} 
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "kubenetmon-agent.fullname" . }}
  labels:
    {{- include "kubenetmon-agent.labels" . | nindent 4 }}
spec:
  podMetricsEndpoints:
    - port: metrics
  selector:
    matchLabels:
      {{- include "kubenetmon-agent.selectorLabels" . | nindent 6 }}
{{- end }}
