---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  labels:
    {{- include "kubenetmon-server.labels" . | nindent 4 }}
data:
  config.yaml: |-
    metrics_port: {{ .Values.metrics.port }}
    grpc_port: {{ .Values.service.port }}
    environment: {{ .Values.environment }}
    cloud: {{ .Values.cloud }}
    region: {{ .Values.region }}
    cluster: {{ .Values.cluster }}
    max_grpc_connection_age: {{ .Values.maxGRPCConnectionAge }}
    num_inserter_workers: {{ .Values.inserter.numInserterWorkers }}
    ignore_udp: {{ .Values.inserter.ignoreUDP }}
    clickhouse_enabled: {{ .Values.inserter.enabled }}
    clickhouse_database: {{ .Values.inserter.database }}
    clickhouse_endpoint: {{ .Values.inserter.endpoint }}
    clickhouse_dial_timeout: {{ .Values.inserter.dialTimeout }}
    clickhouse_max_idle_connections: {{ .Values.inserter.maxIdleConnections }}
    clickhouse_batch_size: {{ .Values.inserter.batchSize }}
    clickhouse_batch_send_timeout: {{ .Values.inserter.batchSendTimeout }}
    clickhouse_wait_for_async_insert: {{ .Values.inserter.waitForAsyncInsert }}
    clickhouse_skip_ping: {{ .Values.inserter.skipPing }}
    clickhouse_disable_tls: {{ .Values.inserter.disableTLS }}
