apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubenetmon-server.fullname" . }}
  labels:
    {{- include "kubenetmon-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "kubenetmon-server.selectorLabels" . | nindent 4 }}
