image:
  repository: local/kubenetmon
  pullPolicy: IfNotPresent
  tag: ""

automountServiceAccountToken: true
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceMonitors:
  enabled: false
  interval: 30s

metrics:
  enabled: true
  port: 8883
  primaryAlerter: false

service:
  type: ClusterIP
  port: 8884

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

resources:
  limits:
    cpu: 2000m
    memory: 2512Mi
  requests:
    cpu: 500m
    memory: 1Gi

nodeSelector: {}

tolerations: []

configuration: {}

secrets: {}

environment: ""
cloud: ""
region: ""
cluster: ""
maxGRPCConnectionAge: 300s

inserter:
  enabled: true
  database: "default"
  endpoint: "clickhouse.default.svc.cluster.local:9000"
  username: "default"
  password: ""
  dialTimeout: 30s
  maxIdleConnections: 50
  batchSize: 15000
  batchSendTimeout: 30s
  waitForAsyncInsert: false

  numInserterWorkers: 20
  ignoreUDP: true
  # Skip pinging ClickHouse on startup. This is useful to skip in test
  # environments where ClickHouse isn't spun up.
  skipPing: false
  # Disable TLS to ClickHouse. This is useful for testing.
  disableTLS: false

deployment:
  replicaCount: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - kubenetmon-server
          topologyKey: kubernetes.io/hostname
