{{- if .Values.priorityClass.enabled }}
---
apiVersion: scheduling.k8s.io/v1
description: Used for kubenetmon-agent to ensure pods are scheduled
kind: PriorityClass
metadata:
  name: {{ .Values.priorityClass.name }}
  labels:
    {{- include "kubenetmon-agent.labels" . | nindent 4 }}
preemptionPolicy: {{ .Values.priorityClass.preemptionPolicy }}
value: {{ int64 .Values.priorityClass.value }}
{{- end }}
